//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgretmenBulv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOzgecmis
    {
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string Okul { get; set; }
        public string Fakulte { get; set; }
        public string Bolum { get; set; }
        public string DeneyimYil { get; set; }
        public string Ozgecmis { get; set; }
        public string AktifDurum { get; set; }
        public string GonderimTarih { get; set; }
    }
}
