//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgretmenBulv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSehirSecim
    {
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string SehirBir { get; set; }
        public string Sehiriki { get; set; }
        public string SehirUc { get; set; }
        public string SehirDort { get; set; }
        public string SehirBes { get; set; }
        public string AktifDurum { get; set; }
        public string Tarih { get; set; }
    }
}
