//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgretmenBulv5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUniversite
    {
        public int ID { get; set; }
        public string UniversiteAd { get; set; }
        public string Aktif { get; set; }
        public string UstGrupID { get; set; }
        public string UniquidKolon1 { get; set; }
        public string tabloguid { get; set; }
    }
}
